#ifndef __config_H__
#define __config_H__

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define SCALING_FACTOR 200


// element configs
#define INBOX_PADDING 0.05

// main page configs
#define MAIN_PAGE_PANEL_RATIO 0.35

#define MAIN_PAGE_LEFT_PANEL_COLOR (Color){24,28,79,255}
#define MAIN_PAGE_LEFT_PANEL_WIDTH SCREEN_WIDTH * MAIN_PAGE_PANEL_RATIO
#define MAIN_PAGE_LEFT_PANEL_HEIGHT SCREEN_HEIGHT
#define MAIN_PAGE_LEFT_PANEL_START (Vector2){0,0}

#define MAIN_PAGE_RIGHT_PANEL_COLOR (Color){2,0,51,255}
#define MAIN_PAGE_RIGHT_PANEL_WIDTH SCREEN_WIDTH * (float)(1 - MAIN_PAGE_PANEL_RATIO)
#define MAIN_PAGE_RIGHT_PANEL_HEIGHT SCREEN_HEIGHT
#define MAIN_PAGE_RIGHT_PANEL_START (Vector2){SCREEN_WIDTH * MAIN_PAGE_PANEL_RATIO,0}

// need to define add position button, title box,description box, done or not button, date box, and time box

#define MAIN_PAGE_ADD_POSITION_BUTTON_COLOR (Color){0,0,0,255}
#define MAIN_PAGE_ADD_POSITION_BUTTON_WIDTH MAIN_PAGE_LEFT_PANEL_WIDTH*0.2
#define MAIN_PAGE_ADD_POSITION_BUTTON_HEIGHT 50
#define MAIN_PAGE_ADD_POSITION_BUTTON_START (Vector2){MAIN_PAGE_LEFT_PANEL_WIDTH*0.95 - MAIN_PAGE_ADD_POSITION_BUTTON_WIDTH, SCREEN_HEIGHT*0.05}

#define MAIN_PAGE_TITLE_BOX_COLOR1 (Color){0,0,0,255}
#define MAIN_PAGE_TITLE_BOX_COLOR2 (Color){255,255,255,255}
#define MAIN_PAGE_TITLE_BOX_WIDTH MAIN_PAGE_LEFT_PANEL_WIDTH*0.3
#define MAIN_PAGE_TITLE_BOX_HEIGHT 50
#define MAIN_PAGE_TITLE_BOX_PLACEHOLDER "Title"
#define MAIN_PAGE_TITLE_BOX_START (Vector2){MAIN_PAGE_LEFT_PANEL_WIDTH*0.05, SCREEN_HEIGHT*0.05}

#define MAIN_PAGE_DATE_BOX_COLOR1 (Color){0,0,0,255}
#define MAIN_PAGE_DATE_BOX_COLOR2 (Color){255,255,255,255}
#define MAIN_PAGE_DATE_BOX_WIDTH MAIN_PAGE_LEFT_PANEL_WIDTH*0.3
#define MAIN_PAGE_DATE_BOX_HEIGHT 50
#define MAIN_PAGE_DATE_BOX_PLACEHOLDER "Date"
#define MAIN_PAGE_DATE_BOX_START (Vector2){MAIN_PAGE_LEFT_PANEL_WIDTH*0.05, SCREEN_HEIGHT*0.15}

#define MAIN_PAGE_DESCRIPTION_BOX_COLOR1 (Color){0,0,0,255}
#define MAIN_PAGE_DESCRIPTION_BOX_COLOR2 (Color){255,255,255,255}
#define MAIN_PAGE_DESCRIPTION_BOX_WIDTH MAIN_PAGE_LEFT_PANEL_WIDTH*0.9
#define MAIN_PAGE_DESCRIPTION_BOX_HEIGHT 300
#define MAIN_PAGE_DESCRIPTION_BOX_START (Vector2){MAIN_PAGE_LEFT_PANEL_WIDTH*0.05, SCREEN_HEIGHT*0.4}



#endif // __config_H__